### ISSUE TITLE
Errors in data_conversion.py using 3D slicer

### ISSUE THREAD

**Issue by Jennieyy** [KCL-BMEIS/VS_Seg#10]
hello, when I use preprocess/data_conversion.py to convert the DICOM images to NIFTI, I encounter an error.
Firstly, I open the python script as a Pycharm Project, and I change the Python Interpreter (System Interpreter) to the D:/Slicer5.6.2/bin/PythonSlicer.exe, the path in 3D Slicer archive.
Secondly, I run the python script aforementioned.
Then, I encounter the error
`"D:\Slicer 5.6.2\bin\PythonSlicer.exe" D:\Dataset_preprocess\TCIA_VS_SEG\data_conversion.py -i D:/Dataset/VS_SEG/ -o D:/Dataset/VS_SEG1/ 
No module named 'logic'
Traceback (most recent call last):
  File "D:\Dataset_preprocess\TCIA_VS_SEG\data_conversion.py", line 48, in <module>
    from DICOMLib import DICOMUtils
  File "D:\Slicer 5.6.2\lib\Slicer-5.6\qt-scripted-modules\DICOMLib\__init__.py", line 1, in <module>
    from .DICOMProcesses import *
  File "D:\Slicer 5.6.2\lib\Slicer-5.6\qt-scripted-modules\DICOMLib\DICOMProcesses.py", line 38, in <module>
    class DICOMProcess:
  File "D:\Slicer 5.6.2\lib\Slicer-5.6\qt-scripted-modules\DICOMLib\DICOMProcesses.py", line 84, in DICOMProcess
    def start(self, cmd: str, args: list[str]) -> qt.QProcess:
AttributeError: module 'qt' has no attribute 'QProcess'

Process finished with exit code 1`
So, I doubt whether that I use the PythonSlicer.exe as Python Interpreter is correct.

**Comment by aaronkujawa** [comment]
Hi, it seems you omitted the `--python-script` argument in your initial command?
