### ISSUE TITLE
data preprocessing

### ISSUE THREAD

**Issue by yingmuzhi** [KCL-BMEIS/VS_Seg#7]
Goodmorning, when I was doing data preprocessing , to  convert DICOM images to NIFTI, it raise an error. It's very nice of you to help me solve this problem, thanks.

```bash
Switch to module:  "Welcome"
TagCacheDatabase adding table

['1']
case: 1
TagCacheDatabase adding table

W: DcmItem: Length of element (4923,736e) is odd
E: DcmElement: Unknown Tag & Data (4923,736e) larger (1952999273) than remaining bytes in file
Could not load  "/Users/yingmuzhi/fsdownload/target/vs_gk_1_t1/inv_T1_LPS_to_T2_LPS.tfm" 
DCMTK says:  I/O suspension or premature end of stream
Could not read DICOM file:/Users/yingmuzhi/fsdownload/target/vs_gk_1_t1/inv_T1_LPS_to_T2_LPS.tfm
E: DcmElement: Unknown Tag & Data (0a5b,7b20) larger (572530698) than remaining bytes in file
Could not load  "/Users/yingmuzhi/fsdownload/target/vs_gk_1_t1/contours.json" 
DCMTK says:  I/O suspension or premature end of stream
Could not read DICOM file:/Users/yingmuzhi/fsdownload/target/vs_gk_1_t1/contours.json
"DICOM indexer has successfully inserted 123 files [0.09s]"
"DICOM indexer has successfully processed 125 files [0.50s]"
"DICOM indexer has updated display fields for 123 files [0.04s]"
W: DcmItem: Length of element (4923,736e) is odd
E: DcmElement: Unknown Tag & Data (4923,736e) larger (1952999273) than remaining bytes in file
Could not load  "/Users/yingmuzhi/fsdownload/target/vs_gk_1_t2/inv_T2_LPS_to_T1_LPS.tfm" 
DCMTK says:  I/O suspension or premature end of stream
Could not read DICOM file:/Users/yingmuzhi/fsdownload/target/vs_gk_1_t2/inv_T2_LPS_to_T1_LPS.tfm
E: DcmElement: Unknown Tag & Data (0a5b,7b20) larger (572530698) than remaining bytes in file
Could not load  "/Users/yingmuzhi/fsdownload/target/vs_gk_1_t2/contours.json" 
DCMTK says:  I/O suspension or premature end of stream
Could not read DICOM file:/Users/yingmuzhi/fsdownload/target/vs_gk_1_t2/contours.json
"DICOM indexer has successfully inserted 83 files [0.06s]"
"DICOM indexer has successfully processed 85 files [0.32s]"
"DICOM indexer has updated display fields for 83 files [0.02s]"
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "<string>", line 531, in <module>
  File "<string>", line 440, in main
  File "<string>", line 144, in import_T1_and_T2_data
AssertionError: Not exactly 4, but 2 files selected for loading of case 1. 
Selected files are ['2: t1_mpr_tra_gk_v4', '4: t2_ci3d_tra_1.5mm_v1']
```

**Comment by yingmuzhi** [comment]
Hi,  I missed the toolkit "SlicerRT".After I install this toolkit ,the code successfully worked on both Mac and Windows10. cool.

**Comment by aaronkujawa** [comment]
Hi, great, thanks for posting the solution!

**Comment by sahikabetul** [comment]
Hello, I had the same problem. And when I try to download, get an error that failed to download extension. Which version of 3D Slicer do yo use?
